### ISSUE TITLE
Dagger modules that are interfaces are treated as component interfaces

### ISSUE THREAD

**Issue by gabrielittner** [square/hephaestus#14]
If you have a module that is an interface Hephaestus will treat it as component interface and make the component extend it.

This can be reproduced by changing `FatherProviderModule` in the sample to an interface. You'll get this error:

`
hephaestus-main/sample/app/build/tmp/kapt3/stubs/debug/com/squareup/hephaestus/sample/AppComponent.java:9: error: [com.squareup.hephaestus.sample.father.FatherProviderModule.bindFatherProvider(com.squareup.hephaestus.sample.father.RealFatherProvider)] Members injection methods may only return the injected type or void.
public abstract interface AppComponent extends com.squareup.hephaestus.sample.DescriptionComponent, com.squareup.hephaestus.sample.father.FatherProviderModule {`

**Comment by vRallev** [comment]
I did not know that interfaces can be used for modules. I only thought abstract classes are allowed. When did this happen? It makes sense, though.

**Comment by ZacSweers** [comment]
It's been possible for years, definitely not a new thing :)

**Comment by ursusursus** [comment]
OT: What is it good for? Your library module doesnt need to provide anything, just the implementing app needs to stuff `fun foo(): Foo = FooImpl` into graphs "from the top", right?
