### ISSUE TITLE
FR: Module -> Module contribution

### ISSUE THREAD

**Issue by ZacSweers** [square/hephaestus#15]
A common case I've run into is wanting to have modules contribute to other modules, rather than components. I often use modules that are intentionally reusable, and generating a module that contributes to them would be immensely helpful.

```kotlin
@Module
class DataModule { .. }

@Module
@ContributesTo(DataModule::class)
class VariantDataModule { .. }

// Results in 
@Module(includes = [VariantDataModule::class])
class DataModule { .. }

```

**Comment by vRallev** [comment]
There is an annotation for this `@MergeModules` and `@MergeInterfaces`. Does this solve your use case?
```
@MergeModules(AppScope::class)
abstract class AppModule
```
This annotation will generate the annotation `@dagger.Module`.

**Comment by ZacSweers** [comment]
Looks like it! Will dig and re-open if need be
