### ISSUE TITLE
Mark usages of capitalize with @OptIn.

### ISSUE THREAD

**Issue by rodgavila** [square/hephaestus#20]
When trying to use the plugin in Gradle I'm getting the following error:

`Unable to find method 'kotlin.text.StringsKt.capitalize(Ljava/lang/String;Ljava/util/Locale;)Ljava/lang/String;'
kotlin.text.StringsKt.capitalize(Ljava/lang/String;Ljava/util/Locale;)Ljava/lang/String;`

Can we mark those as (https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/-opt-in/) do there's no need to add a global `-Xopt-in=kotlin.ExperimentalStdlibApi`?

**Comment by vRallev** [comment]
Curious what you do to see this error? Is there an easy way to reproduce this?

**Comment by rodgavila** [comment]
I tried to get a min-repro but I couldn't. Looks like someone else hit that here: https://github.com/square/hephaestus/issues/8#issuecomment-648736909
