### ISSUE TITLE
General advice on structuring

### ISSUE THREAD

**Issue by ursusursus** [square/hephaestus#26]
Hi.
I know this is not really an issue, but this library implies it.

I presume since you made this library, your issue was a multi-module project, and you got sick of attaching partial component interfaces + modules onto the implementing "merged" component in `:app`.

My question is -- should it even be a thing? i.e. should library modules own their DI stuff? Shouldn't it only be `:app` concern? `Retrofit` doesnt provide a dagger module, so why should my let's say `:payments` do that?

I'm toying with this idea. I kind of like it. But then again, if I were to implement this, and presuming the multi-module project is multiple apps, not just one, I'd need to duplicate a lot of dagger module provider functions etc, per app

**Comment by vRallev** [comment]
Implementations should be isolated and only expose an API. Other features should not rely on implementation details but reuse the APIs instead. This way you achieve low coupling and high cohesion. We create Dagger modules in the implementation modules, because only the implementation "knows" which types it implements. We also share and reuse Dagger modules. 

I gave a talk about our exact module structure a few months ago: https://www.droidcon.com/media-detail?video=380843878
Slides: https://speakerdeck.com/vrallev/android-at-scale-at-square

I hope that clarifies it a little bit.

Since this isn't a real issue as you mentioned I close this issue. I'm happy to reply nonetheless.

**Comment by ursusursus** [comment]
Lol, exactly what I do. I split my `payments` into `:payments:contract` with nothing but interfaces, and `:payments:impl` with implementations and dagger module

However I only did it from fear of circular dependencies + means of being able to refactor monolithic `legacy` module, since now legacy can depend on payments:contract, and payments:impl can depend on legacy. 

Works, but still unsure how is `payments` different from for example `Retrofit`. They don't split anything. Maybe after completing the refactor in time, and `legacy` no longer existing, maybe the split will become obsolete?

Btw where do you have the partial component interfaces? also `:impl` ?

**Comment by vRallev** [comment]
The contributed component interfaces can live in any module, sometimes even `:public`. Often they're used in instrumentation tests. The merged components live in the app module.

**Comment by ursusursus** [comment]
Hmm a 3rd module. I was wondering if they belong to `contract` since they are sort of a public api, but then with hephaestus it pulls a kapt dependency, maybe a 3rd `component` module can do

**Comment by vRallev** [comment]
There is no separate module for component interfaces. They can be in any module and Hephaestus picks them up when compiling the Dagger components. They don't belong into the `:public` module, because often they're an implementation detail (when they're only used in `:impl`). Other implementations might not need these interfaces.

**Comment by ursusursus** [comment]
I'd mostly agree, but there are some edge cases when you need to pull the dependency via getter on component, hence my question.

But now what I think about it, workaround would be to create a FooBar object which participates in the DI graph as one normally would, and which depends on the stuff needed, and only exposes that via a getter on it self, mimicking such component interface

**Comment by ursusursus** [comment]
I've watched your talk, it's really nice

One more thing I'd like to ask, is, do you put UI/Presenters inside a such `:impl`? Or do you separate it into and ui and non-ui modules like `:payments-ui` and `:payments:(contract/impl/wiring)`

**Comment by vRallev** [comment]
Don't overcomplicate it. We don't separate UI in a different module unless it's necessary. Most of the time it's not and there is little value. How we separate presenters (Workflows) is in the slides: https://speakerdeck.com/vrallev/android-at-scale-at-square?slide=53

**Comment by ursusursus** [comment]
That however means if somebody wants just to access PaymentRepository from `:payments:public`, they'll get the UI stuff from `:payments:impl` at runtime as well, accessible possibly by reflection, and/or xmls in the binary, blowing up the apk, right?

**Comment by vRallev** [comment]
I meant Workflows and UI stay in the same module usually. Separating the data makes sense sometimes.

**Comment by ursusursus** [comment]
Right, as I thought, thanks.

One last thing which bother me is actual folder structure. Nesting folder vs. flat hyphenated, i.e. `:payments:contract` vs `:payments-contract`. I can tell you prefer the former, I do too. 

However, imagine there are 2 apps living in the monorepo; and there is a new business feature coming to the App A, lets say it uses OCR, so you create a `ocr:contract/impl` and put related data stuff there. 

Part 1)
Where on disc, would you place the `ocr` folder? In the repository root as to future proof? Or inside `app-a` folder since only that app uses the feature? If you put it in root, then when App B decides to use it, its just 1 line gradle include. However, it might never get around to using it, and then its only uglyfying repo root; but if it does, then moving it to root will cause a massive PR diff

Part 2)
Lets say App B decides to use it, and there are bits and pieces of actual UI/Presenters that can be shared between apps. Where do you put these? "Next to" the `:ocr` module, i.e. `:ocr-ui` int root. OR _inside_ the `ocr` folder? If inside, does that make me adjust the stuff already there by moving those into `ocr:data:contract/impl` + `ocr:ui:contract/impl`?
