### ISSUE TITLE
Fails when using gradle worker api

### ISSUE THREAD

**Issue by rharter** [square/hephaestus#31]
Using the Gradle worker api, each worker gets it's own classpath, so trying to run Hephaestus fails with the following error message.

```
Cannot set the value of task ':some:module:compileReleaseKotlinCheckIncrementalCompilationHephaestus' property 'incrementalSignal' of type com.squareup.hephaestus.plugin.IncrementalSignal using a provider of type com.squareup.hephaestus.plugin.IncrementalSignal.
```

This is in a project with kapt using the worker API, and Room.

I've attempted to implement this in my [branch here](https://github.com/rharter/hephaestus/tree/rh/worker_registry), but need to take off for the day.

**Comment by vRallev** [comment]
I wonder if you could provide a sample project? The worker API is enabled for this project, but I don't see the issue. Maybe it's related to Room?

**Comment by rharter** [comment]
You're right.  While creating a minimally reproducible project, it looks like using gradle kts scripts is what changes things.

Attached is a project that reproduces the issue.  There isn't even any consumption of code, it simply appears that using kts, kapt, and Hephaestus causes the problem.

[Hephalumps.zip](https://github.com/square/hephaestus/files/4949221/Hephalumps.zip)

To see the issue, run `./gradlew assemble` in this project.  To see the fix, alternate the comments in `settings.gradle` so the groovy based module2 is included instead of the kts based module1 is included.

**Comment by vRallev** [comment]
I can reproduce the issue with your project. But I wasn't able to reproduce it in here. This definitely seems to be a Gradle issue  and is maybe caused by the way plugins are applied.

You do this:
```
plugins {
    id("com.squareup.hephaestus").version("1.0.3")
}

apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply plugin: 'kotlin-android-extensions'
apply plugin: 'kotlin-kapt'
```

I changed it to the following in all three modules and cannot reproduce the bug anymore:
```
apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply plugin: 'kotlin-android-extensions'
apply plugin: 'kotlin-kapt'
apply plugin: 'com.squareup.hephaestus'
```

I also tested the plugins syntax and the issue is gone:
```
plugins {
    id("kotlin")
    id("kotlin-kapt")
    id("com.squareup.hephaestus")
}
```

Only mixing the two seems to cause issues.

**Comment by rharter** [comment]
Hmm, that doesn't seem right.  The code you're sharing looks like groovy (notice the single quotes).

In the example, the groovy modules aren't a problem, it's the kts build file that introduces the problem. (comment that out in settings.gradle and the problem goes away.)

[Hephalumps 2.zip](https://github.com/square/hephaestus/files/4951135/Hephalumps.2.zip)

Here's a new repro project with the updates you propose (changing all modules to use new plugin syntax) and the problem persists as long as you include the kts based module in the build.

**Comment by vRallev** [comment]
Sharing zips isn't fun. This for some reason fixes the issue: https://github.com/vRallev/issue-33/commit/0a0c051b558f9a943a3ab81f96acf26e3c5f8960
