### ISSUE TITLE
Love the project - Different name?

### ISSUE THREAD

**Issue by chrisjenx** [square/hephaestus#34]
Love the project works great!!

I really struggle with the name, I'm guessing I'm not the only one? - I personally have to Google for Square's Github org and search for it that way... maybe don't change the name but come up with a short hand or something more SEO friendly?

Dyslexic and non-native English speakers will thank you tremendously 💚

**Comment by vRallev** [comment]
https://github.com/square/hephaestus/issues/12#issuecomment-648975256 You'll get used to the name :-) (BTW, English is my 2nd language, this applies to many other project names, too).
